### ISSUE TITLE
ScreenSelectMusic

### ISSUE THREAD

**Issue by oatmealine** [femboyindustries/gimmick-theme#1]
- tech
  - [ ] wheel item rendering
    - [x] popout ease
      - [ ] possibly tweak to make it less stiff
      - [x] fix the rare double-select w/ roulettes and whatever
    - [x] songs
    - [x] groups
    - [x] roulette/portal/random
    - [x] sorting
    - [ ] make text shrink if it becomes too large
    - [ ] grades / score
      - i think ideally, we'd have some simple light on the side, IIDX-style, representing a pass, fail, fc, etc condensed into a color. slightly unintuitive, but easy to figure out with enough time, so it's justifiable
    - [x] difficulty display
      - [ ] make the default difficulty selected stable, maybe look into sm source code to see what exactly determines it?
    - [ ] bulb for fc/pass/fail/not played
      - [ ] show not played/pass/fc bulbs for groups too
  - [x] difficulty wheel
    - [ ] locked charts (waiting on nitg v4.4/v5 for SongIsLocked)
    - [ ] crop text to bar size
    - [ ] zoom out rating based on size
    - [x] rip out into its own abstracted Thing

- graphics
  - [ ] wheel items
  - [ ] infobar
    - soo much for this one. not even bothering listing it out
  - [x] difficulty wheel
  - [x] difficulty bar
    - [ ] indicators for selecting the correct difficulty
  - [ ] background

**Comment by Luamnoxu** [comment]
Change Draworder to have the Difficulty Circle under SongWheel to prevent
![image](https://github.com/user-attachments/assets/5e115d25-2aaa-48b7-b3dc-fc04df52aa46)

**Comment by oatmealine** [comment]
it's so funny though

**Comment by Luamnoxu** [comment]
i want to see my songs jill oatmealine monoids
its quite literally 1984 like it says (okay that is funny)

(like really funny)

(still)

**Comment by oatmealine** [comment]
![image](https://github.com/user-attachments/assets/05abf5c1-5ef6-4619-8000-026b495ae9b6)
need to mess with subtitle positioning so this doesn't happen

**Comment by oatmealine** [comment]
![image](https://github.com/user-attachments/assets/116f4dcd-82c2-4008-8293-604b4b02fff2)
this displays wrong for some reason

**Comment by oatmealine** [comment]
![image](https://github.com/user-attachments/assets/c1bf636e-c1cd-459f-8b05-2bc2de1d73e8)
what is even happening here
