### ISSUE TITLE
ScreenGameplay

### ISSUE THREAD

**Issue by oatmealine** [femboyindustries/gimmick-theme#15]
- [x] judgements
  - [x] customizable judgement
  - [x] customizable tween
  - [ ] judgement line
  - [ ] tilt based on offset
  - [ ] show offset ms number?
- [x] combo
  - [ ] customizable font
  - [x] glow on fc/fa
    - [ ] ok now do this without stepmania holding my hand the whole time
- [ ] fail overlay
- [ ] custom metamods (#12)
- [x] pause
  - [ ] disqualify on pause
  - [x] fix restart/exit not calling offcommand
  - [x] fix restart/exit not clearing mods
  - [x] fix restart/exit fucking up the noteskin
- [ ] show text when holding start
- [ ] default overlays
  - [ ] score
  - [ ] song length progressbar
  - [ ] lifebar
  - ummm idk what else
- modfile hooking

**Comment by Luamnoxu** [comment]
>  tilt based on offset

please please please make this a preference/setting
personally cannot stand that feature and always revert back to the hardcoded rotations
