### ISSUE TITLE
ScreenEditMenu

### ISSUE THREAD

**Issue by Jecket22** [femboyindustries/gimmick-theme#9]
need to make this list more comprehensive later
- [ ] Design
- [ ] > How is the background loaded in. WHAT did I do here (Fix)
- [ ] > Bar integration similar to ScreenSelectSong
- [ ] Make Banner actually adjustable
> Is it possible to simply encase FadingBanner inside an ActorFrame? idr if ActorFrame has the SetWidth/Height properties
- [ ] Hide Chart varieties, make dance-solo default

**Comment by Luamnoxu** [comment]
What exactly would the Bar do

**Comment by Jecket22** [comment]
good question. what did I think when typing this out at 7 am
